In [4]:
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score

import numpy as np
import tensorflow as tf

import keras
import os
import sys

sys.path.append('..')
import data
import model
import preprocessing
import utils

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Cuarto paso: correr el modelo

In [5]:
l_rates = [0.001, 0.01]
epochs = [10,20,30] #10,20,30
batch_sizes = [8,16,30]#[8,16,30]

experiment = 1 #Número donde inician los experimentos
for batch in batch_sizes:
    for epoch in epochs:
        for learning_rate in l_rates:
        
            print("*"*20)
            print("EXPERIMENTO: Batch:", batch, "Epoc: ", epoch, "learning_rate: ", learning_rate)
            
            #Cargar los parametros cada que inicia un experimento
            params = utils.yaml_to_dict(os.path.join('..','config.yml'))
            params['data_dir'] = os.path.join('..',params['data_dir'])
            
            experiment_name = 'Experimento10-Configuracion'+str(experiment)
            params['model_dir'] = os.path.join('..','experiments-weights',experiment_name)
            params['batch_size'] = batch
            params['num_epochs'] = epoch
            params['learning_rate'] = learning_rate
            
            #Limpiar Sesión
            tf.keras.backend.clear_session()
            
            #Cargar el modelo
            inputs = tf.keras.layers.Input(shape=(110,480,3))
            net = model.ModelArchitecture(num_classes=params['num_classes'])
            x = net(inputs, training=False)
            
            #Generar conjuntos de entrenamiento y validación y llevarlos a un generador
            preprocessing.split_data(params)
            train_generator = data.make_datagenerator(params, mode='training')
            val_generator = data.make_datagenerator(params,mode='validation')
            
            #Crear el directorio que guarda los checkpoints
            if not os.path.exists(params['model_dir']):
                os.makedirs(params['model_dir'])

            #Definir los callbacks
            cp_callback = tf.keras.callbacks.ModelCheckpoint(
                os.path.join(params['model_dir'], 'tf_ckpt'), 
                save_weights_only=True, 
                verbose=1,
                period=5)

            tb_callback = tf.keras.callbacks.TensorBoard(
                os.path.join(params['model_dir'], 'logs'))

            #Definir la función de optimización
            optimizer = tf.keras.optimizers.Adam(params['learning_rate'])

            #Definir los pasos para entrenamiento y validación
            steps_per_epoch = train_generator.n // params['batch_size']
            validation_steps = val_generator.n // params['batch_size']

            #Entrenar el modelo
            net.compile(optimizer=optimizer, loss=params['loss'], metrics=['sparse_categorical_accuracy'])
            net.fit_generator(
                train_generator, 
                steps_per_epoch=steps_per_epoch, 
                epochs=params['num_epochs'],
                workers=4,
                validation_data=val_generator, 
                validation_steps=validation_steps,
                callbacks=[cp_callback,tb_callback])
            
    
            #Obtener las métricas de resultados en el conjunto de validación
            params['batch_size'] = val_generator.n
            params['shuffle'] = False
            val_generator = data.make_datagenerator(params,mode='validation')
            Y_pred = net.predict_generator(val_generator, steps=1)
            y_pred = np.argmax(Y_pred, axis=1)
            
            print(confusion_matrix(val_generator.data, y_pred))
            target_names = ["arranca", "acelera", "pita", "izquierda","frena", "detente", "retrocede", "gira", "avanza", "derecha"]
            print(classification_report(val_generator.data, y_pred, target_names=target_names))
            
            #Aumentar el contador de experimentos
            experiment += 1

********************
EXPERIMENTO: Batch: 8 Epoc:  10 learning_rate:  0.001
Found 2960 images.
Found 30 images.
Epoch 1/10
370/370 [==============================] - 21s 57ms/step - loss: 0.5944 - sparse_categorical_accuracy: 0.8159 - val_loss: 0.3312 - val_sparse_categorical_accuracy: 0.8750
Epoch 2/10
370/370 [==============================] - 21s 58ms/step - loss: 0.1370 - sparse_categorical_accuracy: 0.9571 - val_loss: 0.0801 - val_sparse_categorical_accuracy: 1.0000
Epoch 3/10
370/370 [==============================] - 21s 57ms/step - loss: 0.0717 - sparse_categorical_accuracy: 0.9764 - val_loss: 0.0873 - val_sparse_categorical_accuracy: 0.9583
Epoch 4/10
370/370 [==============================] - 21s 56ms/step - loss: 0.0464 - sparse_categorical_accuracy: 0.9841 - val_loss: 0.0205 - val_sparse_categorical_accuracy: 1.0000
Epoch 5/10
368/370 [============================>.] - ETA: 0s - loss: 0.0340 - sparse_categorical_accuracy: 0.9888- ETA: 4s - loss: 0.03
Epoch 00005: saving mode

370/370 [==============================] - 22s 60ms/step - loss: 0.0819 - sparse_categorical_accuracy: 0.9818 - val_loss: 0.6080 - val_sparse_categorical_accuracy: 0.9167
Found 30 images.
[[2 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0 2 0]
 [0 0 0 0 0 0 0 0 0 2]]
              precision    recall  f1-score   support

     arranca       1.00      1.00      1.00         2
     acelera       1.00      1.00      1.00         4
        pita       1.00      1.00      1.00         4
   izquierda       0.80      1.00      0.89         4
       frena       1.00      0.67      0.80         3
     detente       0.75      1.00      0.86         3
   retrocede       0.75      1.00      0.86         3
        gira       0.00      0.00      0.00         2
      avanza       1.00      0.67      0.80         3
     derecha       0.67      1.00      0

C:\Users\PC\Anaconda3\envs\TensorFlow-GPU-Keras\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Found 2960 images.
Found 30 images.
Epoch 1/20
370/370 [==============================] - 22s 59ms/step - loss: 0.5948 - sparse_categorical_accuracy: 0.8166 - val_loss: 0.4386 - val_sparse_categorical_accuracy: 0.9167
Epoch 2/20
370/370 [==============================] - 23s 63ms/step - loss: 0.1298 - sparse_categorical_accuracy: 0.9598 - val_loss: 0.4110 - val_sparse_categorical_accuracy: 0.9167
Epoch 3/20
370/370 [==============================] - 19s 50ms/step - loss: 0.0746 - sparse_categorical_accuracy: 0.9750 - val_loss: 0.2231 - val_sparse_categorical_accuracy: 0.9583
Epoch 4/20
370/370 [==============================] - 20s 53ms/step - loss: 0.0514 - sparse_categorical_accuracy: 0.9855 - val_loss: 0.2767 - val_sparse_categorical_accuracy: 0.9583
Epoch 5/20
368/370 [============================>.] - ETA: 0s - loss: 0.0280 - sparse_categorical_accuracy: 0.9929
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion3\tf_ckpt

Consider using a TensorFlow opt

370/370 [==============================] - 20s 55ms/step - loss: 0.1291 - sparse_categorical_accuracy: 0.9605 - val_loss: 0.2368 - val_sparse_categorical_accuracy: 0.8750
Epoch 3/20
370/370 [==============================] - 19s 52ms/step - loss: 0.0833 - sparse_categorical_accuracy: 0.9753 - val_loss: 0.1829 - val_sparse_categorical_accuracy: 0.9583
Epoch 4/20
370/370 [==============================] - 18s 48ms/step - loss: 0.0544 - sparse_categorical_accuracy: 0.9838 - val_loss: 0.0273 - val_sparse_categorical_accuracy: 1.0000
Epoch 5/20
369/370 [============================>.] - ETA: 0s - loss: 0.0641 - sparse_categorical_accuracy: 0.9817- ETA: 1s - loss: 0.0526 - sparse_categ
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion4\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
370/370 [==============================] - 18s 49ms/step - loss: 0.0640 - sparse_categorical_accuracy: 0.9818 - val_loss: 0.2834 - val_sparse_categorical_accuracy: 0.

Found 2960 images.
Found 30 images.
Epoch 1/30
370/370 [==============================] - 21s 58ms/step - loss: 0.5806 - sparse_categorical_accuracy: 0.8213 - val_loss: 0.5175 - val_sparse_categorical_accuracy: 0.9167
Epoch 2/30
370/370 [==============================] - 19s 50ms/step - loss: 0.1290 - sparse_categorical_accuracy: 0.9635 - val_loss: 0.2938 - val_sparse_categorical_accuracy: 0.9167268 - sparse_categ
Epoch 3/30
370/370 [==============================] - 18s 48ms/step - loss: 0.0905 - sparse_categorical_accuracy: 0.9672 - val_loss: 0.4329 - val_sparse_categorical_accuracy: 0.8750
Epoch 4/30
370/370 [==============================] - 19s 51ms/step - loss: 0.0515 - sparse_categorical_accuracy: 0.9851 - val_loss: 0.1211 - val_sparse_categorical_accuracy: 0.9167
Epoch 5/30
368/370 [============================>.] - ETA: 0s - loss: 0.0285 - sparse_categorical_accuracy: 0.9908
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion5\tf_ckpt

Consider usin

370/370 [==============================] - 18s 47ms/step - loss: 1.2242e-04 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.1951 - val_sparse_categorical_accuracy: 0.9583
Epoch 26/30
370/370 [==============================] - 18s 47ms/step - loss: 8.4099e-05 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.2035 - val_sparse_categorical_accuracy: 0.9583
Epoch 27/30
370/370 [==============================] - 19s 53ms/step - loss: 7.2253e-05 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.2095 - val_sparse_categorical_accuracy: 0.9583
Epoch 28/30
370/370 [==============================] - 19s 53ms/step - loss: 6.3178e-05 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.2024 - val_sparse_categorical_accuracy: 0.9583
Epoch 29/30
370/370 [==============================] - 18s 50ms/step - loss: 5.7810e-05 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.2301 - val_sparse_categorical_accuracy: 0.9583
Epoch 30/30
369/370 [============================>.] - ETA: 0s - loss: 5.3815

Epoch 16/30
370/370 [==============================] - 20s 53ms/step - loss: 0.0055 - sparse_categorical_accuracy: 0.9997 - val_loss: 2.1805e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 17/30
370/370 [==============================] - 19s 51ms/step - loss: 0.0055 - sparse_categorical_accuracy: 0.9997 - val_loss: 2.4785e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 18/30
370/370 [==============================] - 19s 50ms/step - loss: 0.0055 - sparse_categorical_accuracy: 0.9997 - val_loss: 2.6077e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 19/30
370/370 [==============================] - 21s 56ms/step - loss: 0.0055 - sparse_categorical_accuracy: 0.9997 - val_loss: 2.7765e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 20/30
368/370 [============================>.] - ETA: 0s - loss: 0.0055 - sparse_categorical_accuracy: 0.9997
Epoch 00020: saving model to ..\experiments-weights\Experimento10-Configuracion6\tf_ckpt

Consider using a TensorFlow optimizer from `tf

185/185 [==============================] - 14s 76ms/step - loss: 0.0074 - sparse_categorical_accuracy: 0.9980 - val_loss: 0.0046 - val_sparse_categorical_accuracy: 1.0000
Found 30 images.
[[2 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 2]]
              precision    recall  f1-score   support

     arranca       1.00      1.00      1.00         2
     acelera       1.00      1.00      1.00         4
        pita       1.00      1.00      1.00         4
   izquierda       1.00      1.00      1.00         4
       frena       1.00      1.00      1.00         3
     detente       1.00      1.00      1.00         3
   retrocede       1.00      1.00      1.00         3
        gira       1.00      1.00      1.00         2
      avanza       1.00      1.00      1.00         3
     derecha       1.00      1.00      1

185/185 [==============================] - 20s 106ms/step - loss: 0.7980 - sparse_categorical_accuracy: 0.7611 - val_loss: 0.1037 - val_sparse_categorical_accuracy: 0.9375
Epoch 2/20
185/185 [==============================] - 19s 100ms/step - loss: 0.1627 - sparse_categorical_accuracy: 0.9527 - val_loss: 0.0815 - val_sparse_categorical_accuracy: 0.9375
Epoch 3/20
185/185 [==============================] - 16s 88ms/step - loss: 0.1001 - sparse_categorical_accuracy: 0.9706 - val_loss: 0.0338 - val_sparse_categorical_accuracy: 1.0000
Epoch 4/20
185/185 [==============================] - 12s 66ms/step - loss: 0.0599 - sparse_categorical_accuracy: 0.9858 - val_loss: 0.0512 - val_sparse_categorical_accuracy: 1.0000
Epoch 5/20
183/185 [============================>.] - ETA: 0s - loss: 0.0413 - sparse_categorical_accuracy: 0.9904
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion9\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [============

185/185 [==============================] - 14s 74ms/step - loss: 0.4832 - sparse_categorical_accuracy: 0.8503 - val_loss: 0.3793 - val_sparse_categorical_accuracy: 0.8125
Epoch 2/20
185/185 [==============================] - 14s 74ms/step - loss: 0.1197 - sparse_categorical_accuracy: 0.9659 - val_loss: 0.1333 - val_sparse_categorical_accuracy: 0.9375
Epoch 3/20
185/185 [==============================] - 13s 71ms/step - loss: 0.0801 - sparse_categorical_accuracy: 0.9733 - val_loss: 0.2011 - val_sparse_categorical_accuracy: 0.8750
Epoch 4/20
185/185 [==============================] - 13s 71ms/step - loss: 0.0576 - sparse_categorical_accuracy: 0.9807 - val_loss: 0.0291 - val_sparse_categorical_accuracy: 1.0000
Epoch 5/20
184/185 [============================>.] - ETA: 0s - loss: 0.0275 - sparse_categorical_accuracy: 0.9898- ETA
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion10\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [========

185/185 [==============================] - 13s 68ms/step - loss: 0.0901 - sparse_categorical_accuracy: 0.9753 - val_loss: 0.0185 - val_sparse_categorical_accuracy: 1.0000
Epoch 4/30
185/185 [==============================] - 11s 62ms/step - loss: 0.0672 - sparse_categorical_accuracy: 0.9818 - val_loss: 0.0453 - val_sparse_categorical_accuracy: 1.0000
Epoch 5/30
183/185 [============================>.] - ETA: 0s - loss: 0.0630 - sparse_categorical_accuracy: 0.9798
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion11\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [==============================] - 13s 71ms/step - loss: 0.0629 - sparse_categorical_accuracy: 0.9801 - val_loss: 0.0402 - val_sparse_categorical_accuracy: 1.0000
Epoch 6/30
185/185 [==============================] - 13s 71ms/step - loss: 0.0282 - sparse_categorical_accuracy: 0.9939 - val_loss: 0.0113 - val_sparse_categorical_accuracy: 1.0000
Epoch 7/30
185/185 [=============

185/185 [==============================] - 11s 61ms/step - loss: 2.0569e-04 - sparse_categorical_accuracy: 1.0000 - val_loss: 8.9469e-04 - val_sparse_categorical_accuracy: 1.0000
Epoch 29/30
185/185 [==============================] - 13s 69ms/step - loss: 1.9776e-04 - sparse_categorical_accuracy: 1.0000 - val_loss: 6.0111e-04 - val_sparse_categorical_accuracy: 1.0000
Epoch 30/30
183/185 [============================>.] - ETA: 0s - loss: 1.5928e-04 - sparse_categorical_accuracy: 1.0000
Epoch 00030: saving model to ..\experiments-weights\Experimento10-Configuracion11\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [==============================] - 13s 72ms/step - loss: 1.6121e-04 - sparse_categorical_accuracy: 1.0000 - val_loss: 6.9704e-04 - val_sparse_categorical_accuracy: 1.0000
Found 30 images.
[[2 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0

185/185 [==============================] - 13s 69ms/step - loss: 0.1021 - sparse_categorical_accuracy: 0.9720 - val_loss: 0.4984 - val_sparse_categorical_accuracy: 0.8125
Epoch 5/30
184/185 [============================>.] - ETA: 0s - loss: 0.0706 - sparse_categorical_accuracy: 0.9820
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion12\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [==============================] - 14s 75ms/step - loss: 0.0702 - sparse_categorical_accuracy: 0.9821 - val_loss: 0.1290 - val_sparse_categorical_accuracy: 0.8750
Epoch 6/30
185/185 [==============================] - 13s 69ms/step - loss: 0.0152 - sparse_categorical_accuracy: 0.9966 - val_loss: 0.6932 - val_sparse_categorical_accuracy: 0.8125
Epoch 7/30
185/185 [==============================] - 12s 66ms/step - loss: 0.0726 - sparse_categorical_accuracy: 0.9882 - val_loss: 0.5602 - val_sparse_categorical_accuracy: 0.8125
Epoch 8/30
185/185 [=============

185/185 [==============================] - 13s 68ms/step - loss: 0.0129 - sparse_categorical_accuracy: 0.9986 - val_loss: 0.1561 - val_sparse_categorical_accuracy: 0.9375
Epoch 18/30
185/185 [==============================] - 13s 73ms/step - loss: 0.0185 - sparse_categorical_accuracy: 0.9983 - val_loss: 0.6506 - val_sparse_categorical_accuracy: 0.8750
Epoch 19/30
185/185 [==============================] - 12s 68ms/step - loss: 0.0783 - sparse_categorical_accuracy: 0.9855 - val_loss: 1.3670 - val_sparse_categorical_accuracy: 0.6875
Epoch 20/30
184/185 [============================>.] - ETA: 0s - loss: 0.0549 - sparse_categorical_accuracy: 0.9868
Epoch 00020: saving model to ..\experiments-weights\Experimento10-Configuracion12\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
185/185 [==============================] - 13s 68ms/step - loss: 0.0546 - sparse_categorical_accuracy: 0.9868 - val_loss: 0.9054 - val_sparse_categorical_accuracy: 0.8750
Epoch 21/30
185/185 [=========

98/98 [==============================] - 8s 81ms/step - loss: 0.0963 - sparse_categorical_accuracy: 0.9728 - val_loss: 0.1490 - val_sparse_categorical_accuracy: 0.9667
Epoch 5/10
97/98 [============================>.] - ETA: 0s - loss: 0.0669 - sparse_categorical_accuracy: 0.9808
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion13\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [==============================] - 8s 85ms/step - loss: 0.0672 - sparse_categorical_accuracy: 0.9810 - val_loss: 0.0959 - val_sparse_categorical_accuracy: 1.0000
Epoch 6/10
98/98 [==============================] - 7s 75ms/step - loss: 0.0472 - sparse_categorical_accuracy: 0.9862 - val_loss: 0.0460 - val_sparse_categorical_accuracy: 1.0000
Epoch 7/10
98/98 [==============================] - 8s 81ms/step - loss: 0.0377 - sparse_categorical_accuracy: 0.9915 - val_loss: 0.0585 - val_sparse_categorical_accuracy: 1.0000
Epoch 8/10
98/98 [=============================

98/98 [==============================] - 9s 94ms/step - loss: 1.1251 - sparse_categorical_accuracy: 0.6619 - val_loss: 0.3769 - val_sparse_categorical_accuracy: 0.8667
Epoch 2/20
98/98 [==============================] - 8s 84ms/step - loss: 0.2454 - sparse_categorical_accuracy: 0.9304 - val_loss: 0.1541 - val_sparse_categorical_accuracy: 0.9333
Epoch 3/20
98/98 [==============================] - 8s 82ms/step - loss: 0.1474 - sparse_categorical_accuracy: 0.9578 - val_loss: 0.0833 - val_sparse_categorical_accuracy: 1.0000
Epoch 4/20
98/98 [==============================] - 8s 82ms/step - loss: 0.0951 - sparse_categorical_accuracy: 0.9760 - val_loss: 0.0658 - val_sparse_categorical_accuracy: 0.9667
Epoch 5/20
97/98 [============================>.] - ETA: 0s - loss: 0.0722 - sparse_categorical_accuracy: 0.9808
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion15\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [=============================

98/98 [==============================] - 8s 85ms/step - loss: 0.0498 - sparse_categorical_accuracy: 0.9869 - val_loss: 0.7688 - val_sparse_categorical_accuracy: 0.9333
Epoch 6/20
98/98 [==============================] - 8s 81ms/step - loss: 0.0370 - sparse_categorical_accuracy: 0.9891 - val_loss: 0.5375 - val_sparse_categorical_accuracy: 0.9000
Epoch 7/20
98/98 [==============================] - 8s 80ms/step - loss: 0.0369 - sparse_categorical_accuracy: 0.9896 - val_loss: 0.6398 - val_sparse_categorical_accuracy: 0.9000
Epoch 8/20
98/98 [==============================] - 8s 82ms/step - loss: 0.0214 - sparse_categorical_accuracy: 0.9946 - val_loss: 0.7676 - val_sparse_categorical_accuracy: 0.8667
Epoch 9/20
98/98 [==============================] - 8s 79ms/step - loss: 0.0115 - sparse_categorical_accuracy: 0.9976 - val_loss: 0.5353 - val_sparse_categorical_accuracy: 0.9333
Epoch 10/20
97/98 [============================>.] - ETA: 0s - loss: 0.0159 - sparse_categorical_accuracy: 0.9973- E

98/98 [==============================] - 11s 116ms/step - loss: 1.1290 - sparse_categorical_accuracy: 0.6844 - val_loss: 0.3346 - val_sparse_categorical_accuracy: 0.9333
Epoch 2/30
98/98 [==============================] - 8s 82ms/step - loss: 0.2301 - sparse_categorical_accuracy: 0.9410 - val_loss: 0.2449 - val_sparse_categorical_accuracy: 0.8667A: 2s - loss: 0.2521 - 
Epoch 3/30
98/98 [==============================] - 10s 99ms/step - loss: 0.1380 - sparse_categorical_accuracy: 0.9595 - val_loss: 0.1336 - val_sparse_categorical_accuracy: 0.9667
Epoch 4/30
98/98 [==============================] - 10s 103ms/step - loss: 0.1009 - sparse_categorical_accuracy: 0.9752 - val_loss: 0.1495 - val_sparse_categorical_accuracy: 0.9333
Epoch 5/30
97/98 [============================>.] - ETA: 0s - loss: 0.0778 - sparse_categorical_accuracy: 0.9792- ETA: 3s - loss: 0.0785 - 
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion17\tf_ckpt

Consider using a TensorFlow optimize

98/98 [==============================] - 10s 98ms/step - loss: 0.0013 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0349 - val_sparse_categorical_accuracy: 0.9667
Epoch 25/30
97/98 [============================>.] - ETA: 0s - loss: 0.0013 - sparse_categorical_accuracy: 1.0000
Epoch 00025: saving model to ..\experiments-weights\Experimento10-Configuracion17\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [==============================] - 8s 82ms/step - loss: 0.0013 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0201 - val_sparse_categorical_accuracy: 1.0000
Epoch 26/30
98/98 [==============================] - 9s 87ms/step - loss: 0.0011 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0327 - val_sparse_categorical_accuracy: 0.9667
Epoch 27/30
98/98 [==============================] - 10s 102ms/step - loss: 0.0010 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0243 - val_sparse_categorical_accuracy: 1.0000
Epoch 28/30
98/98 [======================

98/98 [==============================] - 9s 95ms/step - loss: 0.0648 - sparse_categorical_accuracy: 0.9816 - val_loss: 0.0137 - val_sparse_categorical_accuracy: 1.0000gorical_a
Epoch 5/30
97/98 [============================>.] - ETA: 0s - loss: 0.0360 - sparse_categorical_accuracy: 0.9911
Epoch 00005: saving model to ..\experiments-weights\Experimento10-Configuracion18\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [==============================] - 13s 129ms/step - loss: 0.0356 - sparse_categorical_accuracy: 0.9912 - val_loss: 0.3237 - val_sparse_categorical_accuracy: 0.9000
Epoch 6/30
98/98 [==============================] - 9s 94ms/step - loss: 0.0388 - sparse_categorical_accuracy: 0.9895 - val_loss: 0.0686 - val_sparse_categorical_accuracy: 0.9333
Epoch 7/30
98/98 [==============================] - 10s 106ms/step - loss: 0.0636 - sparse_categorical_accuracy: 0.9827 - val_loss: 0.1447 - val_sparse_categorical_accuracy: 0.9667
Epoch 8/30
98/98 [================

98/98 [==============================] - 11s 114ms/step - loss: 0.0512 - sparse_categorical_accuracy: 0.9888 - val_loss: 0.1371 - val_sparse_categorical_accuracy: 0.9667
Epoch 14/30
98/98 [==============================] - 9s 97ms/step - loss: 0.0195 - sparse_categorical_accuracy: 0.9963 - val_loss: 1.0768e-05 - val_sparse_categorical_accuracy: 1.0000
Epoch 15/30
97/98 [============================>.] - ETA: 0s - loss: 0.0094 - sparse_categorical_accuracy: 0.9983- ETA: 3s - loss: 0.0
Epoch 00015: saving model to ..\experiments-weights\Experimento10-Configuracion18\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [==============================] - 10s 100ms/step - loss: 0.0093 - sparse_categorical_accuracy: 0.9983 - val_loss: 3.4774e-05 - val_sparse_categorical_accuracy: 1.0000
Epoch 16/30
98/98 [==============================] - 11s 111ms/step - loss: 0.0059 - sparse_categorical_accuracy: 0.9997 - val_loss: 7.0370e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch

98/98 [==============================] - 12s 118ms/step - loss: 0.0056 - sparse_categorical_accuracy: 0.9997 - val_loss: 3.2544e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 22/30
98/98 [==============================] - 14s 146ms/step - loss: 0.0056 - sparse_categorical_accuracy: 0.9997 - val_loss: 3.2742e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 23/30
98/98 [==============================] - 8s 86ms/step - loss: 5.9268e-05 - sparse_categorical_accuracy: 1.0000 - val_loss: 2.7855e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 24/30
98/98 [==============================] - 11s 117ms/step - loss: 0.0110 - sparse_categorical_accuracy: 0.9993 - val_loss: 2.7696e-06 - val_sparse_categorical_accuracy: 1.0000
Epoch 25/30
97/98 [============================>.] - ETA: 0s - loss: 0.0056 - sparse_categorical_accuracy: 0.9997
Epoch 00025: saving model to ..\experiments-weights\Experimento10-Configuracion18\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 

97/98 [============================>.] - ETA: 0s - loss: 0.0111 - sparse_categorical_accuracy: 0.9993
Epoch 00030: saving model to ..\experiments-weights\Experimento10-Configuracion18\tf_ckpt

Consider using a TensorFlow optimizer from `tf.train`.
98/98 [==============================] - 11s 112ms/step - loss: 0.0110 - sparse_categorical_accuracy: 0.9993 - val_loss: 1.9073e-06 - val_sparse_categorical_accuracy: 1.0000
Found 30 images.
[[2 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 2]]
              precision    recall  f1-score   support

     arranca       1.00      1.00      1.00         2
     acelera       1.00      1.00      1.00         4
        pita       1.00      1.00      1.00         4
   izquierda       1.00      1.00      1.00         4
       frena       1.00      1.00      1.00         3
     